name: Django Tests

on:
  push:
    branches:
      - main
      - develop
      - testing/*
  pull_request:
    branches:
      - main
      - develop
      - testing/*

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd "pg_isready -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }}" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5433:5433

    steps:   
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r ../requirements.txt
        pip install pytest pytest-django

    - name: Create .env file
      run: |
        echo "DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_PORT=5432" >> .env
        echo "GOOGLE_OAUTH2_CLIENT_SECRET=${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}" >> .env
        echo "SENDGRID_KEY=${{ secrets.SENDGRID_KEY }}" >> .env
        echo "STRIPE_SECRET_KEY_TEST=${{ secrets.STRIPE_SECRET_KEY_TEST }}" >> .env
        echo "PUBLISHABLE_KEY=${{ secrets.PUBLISHABLE_KEY }}" >> .env

    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: "localhost"
        DB_PORT: "5433"
        GOOGLE_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
        SENDGRID_KEY: ${{ secrets.SENDGRID_KEY }}
        STRIPE_SECRET_KEY_TEST: ${{ secrets.STRIPE_SECRET_KEY_TEST }}
        PUBLISHABLE_KEY: ${{ secrets.PUBLISHABLE_KEY }}
      run: |
        . env/bin/activate
        coverage run -m pytest
